-- =========================================================
-- ANALYTICS RESET SCRIPT
-- Truncate all FACT and DIM tables (keep schema)
-- =========================================================

-- First truncate FACT tables
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.FACT_JOB_APPLICATION;
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.FACT_STUDY_SESSIONS;

-- Then truncate DIM tables
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.DIM_COMPANY;
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.DIM_ROLE;
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.DIM_SOURCE;
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.DIM_WORK_ARRANGEMENT;
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.DIM_LOCATION;
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.DIM_DATE;
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.DIM_PROVIDER;
TRUNCATE TABLE IF EXISTS JOBDASH.ANALYTICS.DIM_TOPIC;
