-- ==========================================
-- DIMENSION LOAD SCRIPT (with Industry)
-- Database: JOBDASH.ANALYTICS
-- ==========================================

-- Company Dimension (with Industry)
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_COMPANY AS
SELECT
    ROW_NUMBER() OVER (ORDER BY NVL(COMPANY_NAME,''), NVL(INDUSTRY,'')) AS COMPANY_KEY,
    COMPANY_NAME,
    INDUSTRY
FROM (
    SELECT DISTINCT
        COMPANY_NAME,
        INDUSTRY
    FROM JOBDASH.STG.JOB_APPLICATIONS_STG
    WHERE COMPANY_NAME IS NOT NULL
      AND INDUSTRY IS NOT NULL
);

-- Role Dimension
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_ROLE AS
SELECT
    ROW_NUMBER() OVER (ORDER BY ROLE_TITLE) AS ROLE_KEY,
    ROLE_TITLE
FROM (
    SELECT DISTINCT ROLE_TITLE
    FROM JOBDASH.STG.JOB_APPLICATIONS_STG
    WHERE ROLE_TITLE IS NOT NULL
);

-- Source Dimension
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_SOURCE AS
SELECT
    ROW_NUMBER() OVER (ORDER BY SOURCE) AS SOURCE_KEY,
    SOURCE AS SOURCE_NAME
FROM (
    SELECT DISTINCT SOURCE
    FROM JOBDASH.STG.JOB_APPLICATIONS_STG
    WHERE SOURCE IS NOT NULL
);

-- Work Arrangement Dimension
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_WORK_ARRANGEMENT AS
SELECT
    ROW_NUMBER() OVER (ORDER BY WORK_ARRANGEMENT) AS WORK_KEY,
    WORK_ARRANGEMENT
FROM (
    SELECT DISTINCT WORK_ARRANGEMENT
    FROM JOBDASH.STG.JOB_APPLICATIONS_STG
    WHERE WORK_ARRANGEMENT IS NOT NULL
);

-- Location Dimension
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_LOCATION AS
SELECT
    ROW_NUMBER() OVER (ORDER BY CITY, STATE) AS LOCATION_KEY,
    CITY,
    STATE
FROM (
    SELECT DISTINCT CITY, STATE
    FROM JOBDASH.STG.JOB_APPLICATIONS_STG
    WHERE CITY IS NOT NULL OR STATE IS NOT NULL
);

-- Date Dimension
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_DATE AS
SELECT
    ROW_NUMBER() OVER (ORDER BY FULL_DATE) AS DATE_KEY,
    FULL_DATE,
    YEAR(FULL_DATE)      AS YEAR,
    QUARTER(FULL_DATE)   AS QUARTER,
    MONTH(FULL_DATE)     AS MONTH,
    WEEKOFYEAR(FULL_DATE) AS WEEK_OF_YEAR,
    DAY(FULL_DATE)       AS DAY_OF_MONTH,
    DAYOFWEEK(FULL_DATE) AS DAY_OF_WEEK
FROM (
    SELECT DISTINCT DATE_APPLIED AS FULL_DATE
    FROM JOBDASH.STG.JOB_APPLICATIONS_STG
    WHERE DATE_APPLIED IS NOT NULL
    UNION
    SELECT DISTINCT SESSION_DATE AS FULL_DATE
    FROM JOBDASH.STG.STUDY_LOG_STG
    WHERE SESSION_DATE IS NOT NULL
);

-- Provider Dimension
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_PROVIDER AS
SELECT
    ROW_NUMBER() OVER (ORDER BY PROVIDER) AS PROVIDER_KEY,
    PROVIDER AS PROVIDER_NAME
FROM (
    SELECT DISTINCT PROVIDER
    FROM JOBDASH.STG.STUDY_LOG_STG
    WHERE PROVIDER IS NOT NULL
);

-- Topic Dimension
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_TOPIC AS
SELECT
    ROW_NUMBER() OVER (ORDER BY MAIN_CATEGORY, SUB_CATEGORY, TOPIC) AS TOPIC_KEY,
    MAIN_CATEGORY,
    SUB_CATEGORY,
    TOPIC
FROM (
    SELECT DISTINCT MAIN_CATEGORY, SUB_CATEGORY, TOPIC
    FROM JOBDASH.STG.STUDY_LOG_STG
    WHERE TOPIC IS NOT NULL
);
