-- ====================================
-- DIMENSION TABLES
-- ====================================

-- Company dimension
CREATE OR REPLACE TABLE JOBDASH.ANALYTICS.DIM_COMPANY (
    COMPANY_KEY NUMBER(38,0) PRIMARY KEY,
    COMPANY_NAME VARCHAR,
    INDUSTRY VARCHAR
);


-- Date dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_DATE (
    DATE_KEY NUMBER(38,0) PRIMARY KEY,
    FULL_DATE DATE,
    YEAR NUMBER(38,0),
    QUARTER NUMBER(38,0),
    MONTH NUMBER(38,0),
    DAY_OF_MONTH NUMBER(38,0),
    WEEK_OF_YEAR NUMBER(38,0),
    DAY_OF_WEEK NUMBER(38,0)
);

-- Location dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_LOCATION (
    LOCATION_KEY NUMBER(38,0) PRIMARY KEY,
    CITY VARCHAR,
    STATE VARCHAR
);

-- Provider dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_PROVIDER (
    PROVIDER_KEY NUMBER(38,0) PRIMARY KEY,
    PROVIDER_NAME VARCHAR
);

-- Role dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_ROLE (
    ROLE_KEY NUMBER(38,0) PRIMARY KEY,
    ROLE_TITLE VARCHAR
);

-- Source dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_SOURCE (
    SOURCE_KEY NUMBER(38,0) PRIMARY KEY,
    SOURCE_NAME VARCHAR
);

-- Topic dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_TOPIC (
    TOPIC_KEY NUMBER(38,0) PRIMARY KEY,
    MAIN_CATEGORY VARCHAR,
    SUB_CATEGORY VARCHAR,
    TOPIC VARCHAR
);

-- Work Arrangement dimension
CREATE OR REPLACE TABLE ANALYTICS.DIM_WORK_ARRANGEMENT (
    WORK_KEY NUMBER(38,0) PRIMARY KEY,
    WORK_ARRANGEMENT VARCHAR
);
