-- ====================================
-- FACT TABLES
-- ====================================

-- Job applications fact
CREATE OR REPLACE TABLE ANALYTICS.FACT_JOB_APPLICATION (
    APPLICATION_KEY NUMBER(38,0) PRIMARY KEY,
    APP_ID VARCHAR,
    COMPANY_KEY NUMBER(38,0),
    ROLE_KEY NUMBER(38,0),
    WORK_KEY NUMBER(38,0),
    LOCATION_KEY NUMBER(38,0),
    SOURCE_KEY NUMBER(38,0),
    APPLIED_DATE_KEY NUMBER(38,0),
    STATUS VARCHAR,
    REFERRAL VARCHAR,
    COMPENSATION NUMBER(18,2),
    IS_DELETED VARCHAR,
    LAST_MODIFIED_DATE_KEY NUMBER(38,0)
);

-- Study sessions fact
CREATE OR REPLACE TABLE ANALYTICS.FACT_STUDY_SESSIONS (
    SESSION_KEY NUMBER(38,0) PRIMARY KEY,
    STUDY_ID VARCHAR,
    TOPIC_KEY NUMBER(38,0),
    PROVIDER_KEY NUMBER(38,0),
    SESSION_DATE_KEY NUMBER(38,0),
    PROBLEMS_SOLVED NUMBER(6,2),
    HOURS NUMBER(6,2),
    DIFFICULTY VARCHAR
);
