-- ====================================
-- RAW TABLES
-- ====================================

-- Job applications raw
CREATE OR REPLACE TABLE RAW.JOB_APPLICATIONS_RAW (
    APP_ID VARCHAR,
    COMPANY VARCHAR,
    INDUSTRY VARCHAR,
    SOURCE_PLATFORM VARCHAR,
    DATE_APPLIED DATE,
    APPLICATION_STATUS VARCHAR,
    REFERRAL VARCHAR,
    ROLE_TITLE VARCHAR,
    WORK_ARRANGEMENT VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COMPENSATION NUMBER(18,2),
    LAST_MODIFIED DATE,
    IS_DELETED VARCHAR
);

-- Study log raw
CREATE OR REPLACE TABLE RAW.STUDY_LOG_RAW (
    STUDY_ID VARCHAR,
    SESSION_DATE DATE,
    MAIN_CATEGORY VARCHAR,
    SUB_CATEGORY VARCHAR,
    TOPIC VARCHAR,
    PROVIDER VARCHAR,
    PROBLEMS_SOLVED NUMBER(6,2),
    HOURS NUMBER(6,2),
    DIFFICULTY VARCHAR
);
