-- ====================================
-- STAGING TABLES
-- ====================================

-- Job applications staging
CREATE OR REPLACE TABLE STG.JOB_APPLICATIONS_STG (
    APP_ID VARCHAR,
    COMPANY_NAME VARCHAR,
    INDUSTRY VARCHAR,
    SOURCE VARCHAR,
    DATE_APPLIED DATE,
    APPLICATION_STATUS VARCHAR,
    REFERRAL VARCHAR,
    ROLE_TITLE VARCHAR,
    WORK_ARRANGEMENT VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COMPENSATION NUMBER(18,2),
    LAST_MODIFIED DATE,
    IS_DELETED VARCHAR
);

-- Study log staging
CREATE OR REPLACE TABLE STG.STUDY_LOG_STG (
    STUDY_ID VARCHAR,
    SESSION_DATE DATE,
    MAIN_CATEGORY VARCHAR,
    SUB_CATEGORY VARCHAR,
    TOPIC VARCHAR,
    PROVIDER VARCHAR,
    PROBLEMS_SOLVED NUMBER(6,2),
    HOURS NUMBER(6,2),
    DIFFICULTY VARCHAR
);