CREATE OR REPLACE VIEW JOBDASH.ANALYTICS.VW_JOB_APPLICATIONS AS
SELECT
    fa.APP_ID,
    fa.APPLICATION_KEY,
    fa.STATUS AS APPLICATION_STATUS,
    fa.INTERVIEW_STATUS,   -- ✅ Added new column
    fa.REFERRAL,
    fa.COMPENSATION,
    fa.CREATED_AT,
    d_company.COMPANY_NAME,
    d_role.ROLE_TITLE,
    d_location.CITY,
    d_location.STATE,
    d_source.SOURCE_NAME,
    d_work.WORK_ARRANGEMENT,
    d_date.FULL_DATE AS APPLIED_DATE
FROM JOBDASH.ANALYTICS.FACT_JOB_APPLICATION fa
LEFT JOIN JOBDASH.ANALYTICS.DIM_COMPANY d_company
    ON fa.COMPANY_KEY = d_company.COMPANY_KEY
LEFT JOIN JOBDASH.ANALYTICS.DIM_ROLE d_role
    ON fa.ROLE_KEY = d_role.ROLE_KEY
LEFT JOIN JOBDASH.ANALYTICS.DIM_LOCATION d_location
    ON fa.LOCATION_KEY = d_location.LOCATION_KEY
LEFT JOIN JOBDASH.ANALYTICS.DIM_SOURCE d_source
    ON fa.SOURCE_KEY = d_source.SOURCE_KEY
LEFT JOIN JOBDASH.ANALYTICS.DIM_WORK_ARRANGEMENT d_work
    ON fa.WORK_KEY = d_work.WORK_KEY
LEFT JOIN JOBDASH.ANALYTICS.DIM_DATE d_date
    ON fa.APPLIED_DATE_KEY = d_date.DATE_KEY
WHERE fa.IS_DELETED IN ('N','no') OR fa.IS_DELETED IS NULL;
